name: Bug Report
description: Report a bug in the SwissWeather Card
title: "[BUG] "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for creating a bug report! Please fill out the following fields.

  - type: input
    id: version
    attributes:
      label: Card Version
      description: Which version of the SwissWeather Card are you using?
      placeholder: e.g. 1.0.0
    validations:
      required: true

  - type: dropdown
    id: ha-version
    attributes:
      label: Home Assistant Version
      description: Which version of Home Assistant are you using?
      options:
        - 2025.8.x
        - 2025.7.x
        - 2025.6.x
        - Other
    validations:
      required: true

  - type: dropdown
    id: installation
    attributes:
      label: Installation Method
      description: How did you install the card?
      options:
        - HACS
        - Manual
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Problem Description
      description: Please describe the problem as detailed as possible
      placeholder: |
        1. What did you do?
        2. What did you expect to happen?
        3. What happened instead?
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Paste your card configuration here
      render: yaml
      placeholder: |
        type: custom:swissweather-card
        entity: weather.home
        # more configuration...

  - type: textarea
    id: logs
    attributes:
      label: Logs/Error Messages
      description: Browser console or Home Assistant logs
      render: text
      placeholder: |
        Paste relevant logs or error messages here

  - type: textarea
    id: browser
    attributes:
      label: Browser Information
      description: Browser and version
      placeholder: |
        e.g. Chrome 116.0, Firefox 117.0, Safari 16.6

  - type: checkboxes
    id: terms
    attributes:
      label: Confirmation
      options:
        - label: I have read the [documentation](https://github.com/your-username/ha-swissweather-card)
          required: true
        - label: I have searched for similar issues
          required: true
