name: Feature Request
description: Schlagen Sie eine neue Funktion vor
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Vielen Dank für Ihren Feature-Vorschlag! 

  - type: textarea
    id: problem
    attributes:
      label: Problem/Motivation
      description: Welches Problem löst Ihr Feature?
      placeholder: Als Benutzer möchte ich...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Gewünschte Lösung
      description: Beschreiben Sie die gewünschte Funktionalität
      placeholder: Die Card sollte...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternativen
      description: Haben Sie alternative Lösungen erwogen?
      placeholder: Alternativ könnte man...

  - type: dropdown
    id: priority
    attributes:
      label: Priorität
      description: Wie wichtig ist dieses Feature für Sie?
      options:
        - Niedrig (nice to have)
        - Mittel (würde helfen)
        - Hoch (sehr wichtig)
        - Kritisch (blockiert mich)

  - type: textarea
    id: context
    attributes:
      label: Zusätzlicher Kontext
      description: Screenshots, Mockups oder weitere Informationen
      placeholder: |
        Anhänge, Links oder weitere Details...

  - type: checkboxes
    id: checks
    attributes:
      label: Bestätigung
      options:
        - label: Ich habe nach ähnlichen Feature Requests gesucht
          required: true
        - label: Dieses Feature passt zum Scope der SwissWeather Card
          required: true
